### ISSUE TITLE
`run_on_start` is not actually running the audit

### ISSUE THREAD

**Issue by thbar** [christianhellsten/guard-bundler-audit#5]
It seems like even with `run_on_start: true`, only the database is updated, but the audit is not ran. A quick glance at the code seems to confirm that.

It would be nice to be able to audit on start - do you think it would be a nice addition?

**Comment by christianhellsten** [comment]
Yes, that seems to be the case. It would be a nice addition.

**Comment by ProGM** [comment]
@christianhellsten Can you create a release with this? :)

**Comment by thbar** [comment]
Seconded, would love to use the latest version!

**Comment by christianhellsten** [comment]
Done:
https://rubygems.org/gems/guard-bundler-audit/versions/0.1.4

Sorry for the delay.
